# Generated by Django 4.2.7 on 2023-11-14 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Kategori')),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Resim')),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], default=False, max_length=10, verbose_name='Yayınla')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Ürün')),
                ('keywords', models.CharField(max_length=250)),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='Resim')),
                ('price', models.FloatField(verbose_name='Birim Fiyat')),
                ('amount', models.IntegerField(default=0, verbose_name='Adet')),
                ('detail', models.TextField(verbose_name='Detay')),
                ('status', models.CharField(choices=[('True', 'Evet'), ('False', 'Hayır')], max_length=10, verbose_name='Yayınla')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'verbose_name': 'Ürün',
                'verbose_name_plural': 'Ürünler',
            },
        ),
    ]
