# Generated by Django 4.2.7 on 2023-11-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='keywords',
            field=models.CharField(max_length=250, verbose_name='Anahtar Kelime'),
        ),
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.CharField(max_length=250, verbose_name='Anahtar Kelime'),
        ),
    ]
