# Generated by Django 4.2.7 on 2023-11-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopsetting',
            name='linkedin',
            field=models.CharField(blank=True, max_length=50, verbose_name='Linkedin'),
        ),
    ]
